@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhYmMiLCJleHAiOjE3NDE5MDc5OTR9.xAHT77RXnaZWkmk_TmsJ4s5wPtcoplEUVtAvKCCra5I

### Verbo GET – listar todos
GET http://localhost:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{token}}

### Verbo GET – listar um
GET http://localhost:8000/funcionario/1 HTTP/1.1
Authorization: Bearer {{token}}

### Verbo GET – validar cpj
POST http://localhost:8000/funcionario/login/ HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
"matricula": "lu12353",
"telefone": "tel2383738",
"id_funcionario": 1,
"senha": "ee29eb4a8725678278ac4320e7",
"cpf": "1",
"nome": "Luciano Coelho",
"grupo": 1
}


### Verbo GET – validar cpf
GET http://localhost:8000/funcionario/cpf/1 HTTP/1.1
Authorization: Bearer {{token}}

### Verbo POST – adicionar
POST http://127.0.0.1:8000/funcionario/ HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
"nome" : "Luciano Coelho",
"matricula" : "lu12353",
"cpf" : "1",
"telefone" : "tel2383738",
"grupo" : 1,
"senha" : "ee29eb4a8725678278ac4320e7"
}
### Verbo PUT – atualiza
PUT http://127.0.0.1:8000/funcionario/1 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
"nome" : "Luciano Coelho Editado",
"matricula" : "lu12353-editada",
"cpf" : "1",
"telefone" : "tel2383738",
"grupo" : 1,
"senha" : "dc7378a6b6316017b81c51d720e7"
}
### Verbo DELETE - excluir
DELETE http://127.0.0.1:8000/funcionario/1 HTTP/1.1
Authorization: Bearer {{token}}